/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as InvoicesInvoiceIdIndexRouteImport } from './routes/invoices/$invoiceId/index'
import { Route as InvoicesInvoiceIdEditRouteImport } from './routes/invoices/$invoiceId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdIndexRoute = InvoicesInvoiceIdIndexRouteImport.update({
  id: '/invoices/$invoiceId/',
  path: '/invoices/$invoiceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdEditRoute = InvoicesInvoiceIdEditRouteImport.update({
  id: '/invoices/$invoiceId/edit',
  path: '/invoices/$invoiceId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId/': typeof InvoicesInvoiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices': typeof InvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId/': typeof InvoicesInvoiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoices/new'
    | '/invoices/'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoices/new'
    | '/invoices'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/invoices/new'
    | '/invoices/'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  InvoicesInvoiceIdEditRoute: typeof InvoicesInvoiceIdEditRoute
  InvoicesInvoiceIdIndexRoute: typeof InvoicesInvoiceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId/': {
      id: '/invoices/$invoiceId/'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId/'
      preLoaderRoute: typeof InvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId/edit': {
      id: '/invoices/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof InvoicesInvoiceIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  InvoicesInvoiceIdEditRoute: InvoicesInvoiceIdEditRoute,
  InvoicesInvoiceIdIndexRoute: InvoicesInvoiceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
